// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNCVhzOFYlDGX6xdT1bcGSW5c-IFhcVA',
    appId: '1:617282016317:web:daee963a431223d5e54654',
    messagingSenderId: '617282016317',
    projectId: 'flash-chat-88545',
    authDomain: 'flash-chat-88545.firebaseapp.com',
    storageBucket: 'flash-chat-88545.appspot.com',
    measurementId: 'G-TBSRY2Z1P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuopcdtpYreVyu5fb6940EEn0OqYa9VrI',
    appId: '1:617282016317:android:a55e5e3439c38750e54654',
    messagingSenderId: '617282016317',
    projectId: 'flash-chat-88545',
    storageBucket: 'flash-chat-88545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Nq-rqF8c3Whkya_m9fOsREO0-J5gq4w',
    appId: '1:617282016317:ios:d4288fce22f4db40e54654',
    messagingSenderId: '617282016317',
    projectId: 'flash-chat-88545',
    storageBucket: 'flash-chat-88545.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Nq-rqF8c3Whkya_m9fOsREO0-J5gq4w',
    appId: '1:617282016317:ios:d4288fce22f4db40e54654',
    messagingSenderId: '617282016317',
    projectId: 'flash-chat-88545',
    storageBucket: 'flash-chat-88545.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNCVhzOFYlDGX6xdT1bcGSW5c-IFhcVA',
    appId: '1:617282016317:web:937e299df3bdbb0ee54654',
    messagingSenderId: '617282016317',
    projectId: 'flash-chat-88545',
    authDomain: 'flash-chat-88545.firebaseapp.com',
    storageBucket: 'flash-chat-88545.appspot.com',
    measurementId: 'G-21TRM972K9',
  );

}